name: Generate and Deploy PDF Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Compile PDF Artifact
        run: node src/render.js --output cv

      - name: Upload PDF to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dominick-Robinson-Resume
          path: dist/cv/DOMINICK_ROBINSON_RESUME.pdf